// ClearScope Contract Deployment
// Handles deploying the ClearScope contracts to the Midnight network.
//
// NOTE: The concrete contract classes referenced here are generated by the
// Compact compiler when you run `npm run compile:contracts`. Each
// `contracts/managed/<name>/contract/index.js` file is emitted by `compact
// compile` together with its ZK artifacts under `keys/` and `zkir/`. Until
// that compilation step runs, the concrete generated types do not exist, so
// this layer is written against the generated boundary as `any`.

import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js'
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts'

// A compiled contract as produced by `compact compile`. The concrete generic
// shape (circuit ids, witness shape, private state) is typed by the generated
// `contract/index.js` module; until that module exists this boundary is `any`.
type CompiledContract = ReturnType<typeof CompiledContract.make<never, never, never>>

import {
  holderDateOfBirth,
  holderKYCTier,
  holderJurisdiction,
  witnessAgeFromDOB,
  witnessCheckExclusion,
  witnessParseThreshold,
  witnessParseTier,
  witnessComputeAge,
  witnessCaller,
} from './witnesses'

// Witness implementations are attached to each compiled contract. The shape of
// each object matches the witness declarations in the corresponding .compact
// file. These run locally on the user device and never touch the ledger.
const disclosureRequestWitnesses = {}

const policyRegistryWitnesses = {
  witnessCaller: () => witnessCaller(),
}

const ageThresholdWitnesses = {
  holderDateOfBirth: () => holderDateOfBirth(),
  witnessAgeFromDOB: (dob: string) => witnessAgeFromDOB(dob),
}

const kycTierWitnesses = {
  holderKYCTier: () => holderKYCTier(),
}

const jurisdictionExclusionWitnesses = {
  holderJurisdiction: () => holderJurisdiction(),
  witnessCheckExclusion: (jurisdiction: string, excluded: string) =>
    witnessCheckExclusion(jurisdiction, excluded),
}

const credentialStoreWitnesses = {
  getCredentialAttribute: (credentialId: string, attributeKey: string) => ({
    credentialId,
    issuer: 'Global Identity Corp',
    credentialType: 'Government ID',
    issuedDate: '2024-03-15',
    attributeKey,
    attributeValue: '1995-07-21',
  }),
  witnessParseThreshold: (params: string) => witnessParseThreshold(params),
  witnessParseTier: (params: string) => witnessParseTier(params),
  witnessComputeAge: (dob: string) => witnessComputeAge(dob),
  witnessCheckExclusion: (jurisdiction: string, excluded: string) =>
    witnessCheckExclusion(jurisdiction, excluded),
}

// Relative paths to each contract's compiled output, produced by
// `npm run compile:contracts`.
const CONTRACT_PATHS = {
  disclosureRequest: './contracts/managed/disclosure_request',
  policyRegistry: './contracts/managed/policy_registry',
  ageThreshold: './contracts/managed/age_threshold_v1',
  kycTier: './contracts/managed/kyc_tier_v1',
  jurisdictionExclusion: './contracts/managed/jurisdiction_exclusion_v1',
  credentialStore: './contracts/managed/credential_store',
} as const

type ContractName = keyof typeof CONTRACT_PATHS

interface ContractDeploySpec {
  name: string
  witnesses: Record<string, (...args: unknown[]) => unknown>
  path: string
}

function deploySpec(name: ContractName, witnesses: Record<string, unknown>): ContractDeploySpec {
  return {
    name,
    witnesses: witnesses as Record<string, (...args: unknown[]) => unknown>,
    path: CONTRACT_PATHS[name],
  }
}

// Build a compiled contract from a generated module. The generated module is
// imported lazily so this file typechecks before `compact compile` has run.
// The generated `Contract` class carries the typed circuit and witness shape;
// until compilation runs that type is unknown, so the boundary is `any`.
function loadCompiledContract(spec: ContractDeploySpec): CompiledContract {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const generated = require(`${spec.path}/contract/index.js`).Contract
  const compiled = CompiledContract.withWitnesses(
    CompiledContract.make(spec.name, generated),
    spec.witnesses as never
  ) as any
  return (CompiledContract.withCompiledFileAssets as any)(
    compiled,
    spec.path
  ) as unknown as CompiledContract
}

/**
 * Deploy every ClearScope contract and return their on-chain addresses.
 *
 * @param providers A MidnightProviders object created by createProviders()
 * @returns addresses for the six deployed contracts
 */
export async function deployAllContracts(providers: unknown) {
  const specs: ContractDeploySpec[] = [
    deploySpec('disclosureRequest', disclosureRequestWitnesses),
    deploySpec('policyRegistry', policyRegistryWitnesses),
    deploySpec('ageThreshold', ageThresholdWitnesses),
    deploySpec('kycTier', kycTierWitnesses),
    deploySpec('jurisdictionExclusion', jurisdictionExclusionWitnesses),
    deploySpec('credentialStore', credentialStoreWitnesses),
  ]

  const addresses: Record<string, string> = {}

  for (const spec of specs) {
    console.log(`Deploying ${spec.name} contract...`)
    // The generated contracts with a constructor that takes no arguments have
    // no private state, so the base deploy path applies. Contracts with a
    // constructor or witnesses that maintain private state use the
    // private-state path. The compiled artifacts' type drives which overload
    // is selected at runtime.
    const deployed = await deployContract(providers as never, {
      compiledContract: loadCompiledContract(spec),
      privateStateId: `${spec.name}PrivateState`,
      initialPrivateState: {},
    } as never)
    const address = deployed.deployTxData.public.contractAddress
    addresses[spec.name] = address
    console.log(`${spec.name} deployed at: ${address}`)
  }

  return addresses
}

/**
 * Connect to an already deployed contract by address.
 */
export async function findContract(
  providers: unknown,
  contractAddress: string,
  contractType: ContractName
) {
  const spec = deploySpec(contractType, {})
  const compiledContract = loadCompiledContract(spec)

  return findDeployedContract(providers as never, {
    contractAddress,
    compiledContract,
    privateStateId: `${spec.name}PrivateState`,
    initialPrivateState: {},
  } as never)
}